Enter number of vertices: Enter number of edges: Enter 12 edges in the form `v w` (no quotes):
Number of vertices: 11
Number of edges: 12
Edges:
 0: 1 2 6 7
 1: 0 2
 2: 0 1 3 5
 3: 2 4
 4: 3
 5: 2
 6: 0 7
 7: 0 6 8 10
 8: 7 9
 9: 8
10: 7

Enter the source vertex and maximum distance: numWithin(g, 0, 1) = 5
Enter the source vertex and maximum distance: numWithin(g, 0, 2) = 9
Enter the source vertex and maximum distance: numWithin(g, 0, 3) = 11
Enter the source vertex and maximum distance: numWithin(g, 0, 4) = 11
Enter the source vertex and maximum distance: numWithin(g, 1, 1) = 3
Enter the source vertex and maximum distance: numWithin(g, 1, 2) = 7
Enter the source vertex and maximum distance: numWithin(g, 1, 3) = 10
Enter the source vertex and maximum distance: numWithin(g, 1, 4) = 11
Enter the source vertex and maximum distance: numWithin(g, 4, 1) = 2
Enter the source vertex and maximum distance: numWithin(g, 4, 2) = 3
Enter the source vertex and maximum distance: numWithin(g, 4, 3) = 6
Enter the source vertex and maximum distance: numWithin(g, 4, 4) = 8
Enter the source vertex and maximum distance: numWithin(g, 4, 5) = 10
Enter the source vertex and maximum distance: numWithin(g, 4, 6) = 11
Enter the source vertex and maximum distance: 